### ISSUE TITLE
examples do not work

### ISSUE THREAD

**Issue by rudyavsky-ag** [foolin/gin-template#8]
I try in exaples/multiple
>go run main.go
and get panic:

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> main.main.func2 (3 handlers)
[GIN-debug] GET    /admin/                   --> main.main.func4 (4 handlers)
[GIN-debug] Listening and serving HTTP on :9090

[31m2018/04/19 19:39:32 [Recovery] panic recovered:
GET / HTTP/1.1
Host: 127.0.0.1:9090
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Cache-Control: max-age=0
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

runtime error: invalid memory address or nil pointer dereference
C:/Go/src/runtime/panic.go:491 (0x42c290)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
C:/Go/src/runtime/panic.go:63 (0x42b114)
	panicmem: panic(memoryError)
C:/Go/src/runtime/signal_windows.go:161 (0x4405a2)
	sigpanic: panicmem()
D:/src/golang/src/github.com/foolin/gin-template/template.go:175 (0x777860)
	(*TemplateEngine).executeTemplate: data, err = e.fileHandler(e.config, v)
D:/src/golang/src/github.com/foolin/gin-template/template.go:131 (0x776e75)
	(*TemplateEngine).executeRender: return e.executeTemplate(out, name, data, useMaster)
D:/src/golang/src/github.com/foolin/gin-template/template.go:212 (0x77856b)
	TemplateRender.Render: return r.Engine.executeRender(w, r.Name, r.Data)
<autogenerated>:1 (0x778dc6)
D:/src/golang/src/github.com/gin-gonic/gin/context.go:427 (0x767048)
	(*Context).Render: if err := r.Render(c.Writer); err != nil {
D:/src/golang/src/github.com/gin-gonic/gin/context.go:437 (0x767126)
	(*Context).HTML: c.Render(code, instance)
D:/src/golang/src/github.com/foolin/gin-template/template.go:97 (0x77693f)
	HTML: ctx.HTML(code, name, data)
D:/src/golang/src/gin-template/examples/multiple/main.go:40 (0x7797a0)
	main.func2: gintemplate.HTML(ctx, http.StatusOK, "index", gin.H{
D:/src/golang/src/github.com/gin-gonic/gin/context.go:97 (0x765759)
	(*Context).Next: c.handlers[c.index](c)
D:/src/golang/src/github.com/gin-gonic/gin/recovery.go:45 (0x774760)
	RecoveryWithWriter.func1: c.Next()
D:/src/golang/src/github.com/gin-gonic/gin/context.go:97 (0x765759)
	(*Context).Next: c.handlers[c.index](c)
D:/src/golang/src/github.com/gin-gonic/gin/logger.go:72 (0x773b67)
	LoggerWithWriter.func1: c.Next()
D:/src/golang/src/github.com/gin-gonic/gin/context.go:97 (0x765759)
	(*Context).Next: c.handlers[c.index](c)
D:/src/golang/src/github.com/gin-gonic/gin/gin.go:284 (0x76b7fa)
	(*Engine).handleHTTPRequest: context.Next()
D:/src/golang/src/github.com/gin-gonic/gin/gin.go:265 (0x76b181)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
C:/Go/src/net/http/server.go:2619 (0x6b70ea)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
C:/Go/src/net/http/server.go:1801 (0x6b3183)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
C:/Go/src/runtime/asm_amd64.s:2337 (0x458090)
	goexit: BYTE	$0x90	// NOP
[0m
exit status 2

In all examples i get the same. What is my mistake? I use latest gin-template from github? go 1.9.4 windosw/amd64.

**Comment by foolin** [comment]
sorry, this is a bug. now had fixed!

**Comment by rudyavsky-ag** [comment]
It works. Thanks.
